#!/bin/bash

if [ -z "$ALLURE_HOME" ]; then

    SOURCE="${BASH_SOURCE[0]}"
    while [ -h "$SOURCE" ]; do
        DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
        SOURCE="$(readlink "$SOURCE")"
        [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
    done
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    ALLURE_HOME="$DIR/.."

fi

ALLURE_CLI_JAR="$ALLURE_HOME/lib/allure-cli.jar"

if [ ! -f "$ALLURE_CLI_JAR" ]; then

    echo "$ALLURE_HOME: is not a valid Allure home directory"
    exit 1

fi

java -jar ${ALLURE_CLI_JAR} $@